### ISSUE TITLE
pow for neucoin

### ISSUE THREAD

**Issue by chicloso** [NeuCoin/neucoin#16] opened 2015-09-28 20:46 UTC
you mentione that pow for neucoin will be available in the first year yet there is no set up for that

do you have a deamon that can be used with the wallet?

also your wallet really lacks  you cannot tell if the wallet is staking, you cannot tell the estimated time before reward based on network weight you cannot tell your own coin weight. 
it is really a basic wallet not impresses at all...you really should emulate CON wallet  it offer everything you need to stake a coin properly.

please give me direction here, bought some coin want to stake and mine  but its impossible to find any documentation  !!

**Comment by Magicking** [comment] 2015-09-29 09:51
A basic PoW miner is included within both the daemon and qt client see the FAQ here https://github.com/NeuCoin/neucoin/blob/master/doc/faq.md but a dedicated software and/or hardware should be used.

For daemons see here https://github.com/NeuCoin/neucoin/releases

Staking is enabled by default on both qt and daemon version.

Statistics are a duplicate of #12 

Closing as a non-bug.

**Closed as completed by Magicking** 2015-09-29 09:51 UTC

**Comment by chicloso** [comment] 2015-09-29 14:17
thank you,

you mention that the is a deamon download  but all i see is a wallet
download option  is the deamon included in the download files?

could i use a standard scrypt miner lice cgminer, and point it to my wallet
IP ?
as a standalone mining option ?

**Comment by Magicking** [comment] 2015-09-29 14:26
neucoin-qt stand for neucoin qt and neucoind stand for neucoin daemon.

Regarding cgminer I didn't try with this one particularly but AFAIK it should work.
