### ISSUE TITLE
Keyboard input problem through tightVNC+Ubuntu

### ISSUE THREAD

**Issue by alexandruasandei89** [NeuCoin/neucoin#13] opened 2015-09-26 13:37 UTC
I installed the qt-wallet [1] on a Ubuntu 14.04 in Amazon EC2 and connected through tightVNC. 
The issue is that the keyboard input seems incorrectly mapped when using the debug console. This only happens with neucoin qt-wallet, input in all other applications and terminal works fine.
Client version is: v0.8.0-beta-22-g5a43676-dirty-beta 
Example:
setgenerate = bgnjg\gvang
qwertyuiopasdfghjklzxcvbnm = c.gvnmlzxabfhjk;'`*/d,s\

[1] https://github.com/NeuCoin/neucoin/releases/download/v1.0.0/neucoin-qt_1.0.0_ubuntu_amd64.deb

**Comment by alexandruasandei89** [comment] 2015-09-26 19:23
This might be related to xfce, the packages I used for to enable vnc are: xfce4 xfce4-goodies tightvncserver

**Comment by Magicking** [comment] 2015-09-29 11:16
The problem you are experiencing is Qt not being able to use the keyboard because of  TightVNC not providing XKEYBOARD extension.

Since you are using Ubuntu on a server I would greatly recommend the use of the daemon version instead, if the issue is to keep the daemon launched, you can launch it in a terminal multiplexer (such as tmux) and use the command line interface to operate it.

Closing as a non-bug.

**Closed as completed by Magicking** 2015-09-29 11:16 UTC
