### ISSUE TITLE
Coinstakes are coming too fast

### ISSUE THREAD

**Issue by shday** [NeuCoin/neucoin#17] opened 2015-09-30 01:20 UTC
The following is from the Neucoin white paper:

>   Given NeuCoin's parameters for minimum stake  age and block time, a miner owning 1/50,000 of the total currency supply would be expected to earn a coinstake once per month.

I personally have around 1/100000 of the total supply (30000 coins), but I'm staking every few days. On the form I see people talking about how they've been staking with even less.

Did something change? Why are we staking so fast?

**Comment by arcanis** [comment] 2015-09-30 09:46
Staking depends on a lot of factors - for example, the network supply isn't the number of coins that actually stake. Another thing to take into account is that random variations are expected - some wallets with about the same balance than you have still haven't staked yet.

Closing as not-a-bug, especially since it's more an economical question (that should go on the forum) than a technical one (that should go on this repository).

**Closed as completed by arcanis** 2015-09-30 09:46 UTC

**Comment by shday** [comment] 2015-09-30 11:22
For what it's worth, there seems to be a high percentage of coins staking (2/3 from just two addresses below). So I would rule that out as the cause. Perhaps I was just lucky. I'll post in the forum if it continues.

http://www.neucoin.io/address/NdoQ1quvqEnkNMqtSzVhTKiLrbDuKQYQz6
http://www.neucoin.io/address/NRm3zEZGHMFKeFiqQRPHBrAi667Z3ZG7jt

**Comment by alexhiggins732** [comment] 2015-11-10 05:00
Of course this was closed as not a bug.... huge issue. Once every minute? Nope. I see once see these accounts sporadically staking multiple times a minute... and that's just these two accounts not even the entire network.

**Comment by alexhiggins732** [comment] 2015-11-10 05:02
Not too mention, these stakes stomp all over the everyone else on the block chain. Surely, a less frequent stake time would alleviate the erasure of said erased blocks.

**Comment by Magicking** [comment] 2015-11-10 05:09
- Please use the edit button instead of making several comments.
- By account you are talking about address which doesn't mean anything here since staking take an UTXO not an address.
- "once every minute" is a target not a fixed time frame.
- PoS is prioritized over PoW.
